[tool.black]
line-length = 120

[tool.flake8]
max-line-length = 120
extend-ignore = ["E203"]
max-complexity = 10

[tool.pylint]
max-line-length = 120

[tool.pylint."messages control"]
disable = ["duplicate-code"]

[tool.isort]
profile = "black"
